import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Grievance Report Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col"><main className="flex-1 overflow-y-auto p-8 custom-scrollbar z-0 relative h-full">
        <div
          className="absolute inset-0 opacity-[0.4] dark:opacity-30 pointer-events-none bg-fixed"
          style={{ backgroundImage: 'url("https://www.transparenttextures.com/patterns/diagonal-striped-brick.png")' }}
        />

        <div className='absolute inset-0 overflow-y-auto p-8 custom-scrollbar z-10'>
          {children}
        </div>
      </main></body>
    </html>
  );
}
